name: Create and publish a Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - release
      - main

env:
  REGISTRY: sjc.vultrcr.com
  IMAGE_NAME: seven/fxrate

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false

      - name: Generate artifact attestation (OCI referrers)
        id: attest
        uses: actions/attest-build-provenance@v1
        continue-on-error: true
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Install cosign
        if: steps.attest.outcome == 'failure'
        uses: sigstore/cosign-installer@v3

      - name: Push SLSA attestation with cosign (keyless default)
        if: steps.attest.outcome == 'failure'
        env:
          COSIGN_YES: "true"
        run: |
          cat > predicate.json <<'JSON'
          { "buildType": "https://slsa.dev/container/v1",
            "builder": { "id": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" },
            "invocation": { "configSource": { "entryPoint": ".github/workflows/cd.yml" } }
          }
          JSON
          cosign attest \
            --predicate predicate.json \
            --type slsaprovenance \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }}
