#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  release:
    types: [published]
  push:
    branches:
      - release
      - main

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          # For Docker login, use only the registry hostname
          registry: sjc.vultrcr.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sjc.vultrcr.com/seven/fxrate
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Let actions/attest-build-provenance or cosign handle provenance
          provenance: false

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)."
      - name: Generate artifact attestation (OCI referrers)
        id: attest
        uses: actions/attest-build-provenance@v1
        continue-on-error: true
        with:
          subject-name: sjc.vultrcr.com/seven/fxrate
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      # Fallback: if registry does not support OCI referrers, push SLSA attestation via cosign
      - name: Install cosign
        if: steps.attest.outcome == 'failure'
        uses: sigstore/cosign-installer@v3

      - name: Push SLSA attestation with cosign (keyless default)
        if: steps.attest.outcome == 'failure'
        env:
          COSIGN_YES: "true"
        run: |
          cat > predicate.json <<'JSON'
          { "buildType": "https://slsa.dev/container/v1",
            "builder": { "id": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" },
            "invocation": { "configSource": { "entryPoint": ".github/workflows/cd.yml" } }
          }
          JSON
          cosign attest \
            --predicate predicate.json \
            --type slsaprovenance \
            sjc.vultrcr.com/seven/fxrate@${{ steps.push.outputs.digest }}
